set termguicolors
set background=dark
colorscheme my_colorscheme
syntax enable

set number
set relativenumber
set cursorline

set tabstop=4
set shiftwidth=4
set smartindent
set expandtab

set incsearch
set hlsearch
set ignorecase
set smartcase
set list
set listchars=tab:»\ ,trail:·,nbsp:␣

set makeprg=./build.sh
